energy/energy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^admin/', include(admin.site.urls)),
)

energy/reviews/urls.py
from django.conf.urls import patterns, include, url

from .views import SupplierListView, SupplierReviewListView, create_review

urlpatterns = patterns('',
    url(r'^$', SupplierListView.as_view(), name='suppliers'),
    url(r'^(?P<slug>[\w-]+)/$', SupplierReviewListView.as_view(), name='supplier_reviews'),
    url(r'^(?P<slug>[\w-]+)/write$', create_review, name='create_review'),
)

energy/reviews/models.py
from datetime import datetime

from django.db import models
from django.template.defaultfilters import slugify

class TimeStampedModel(models.Model):
    """
    Abstract base class model with auto-updating created and last modified fields
    """
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Supplier(TimeStampedModel):
    """ Model representing a Supplier """
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        # Only gen slug when creating object, so it doesn't change
        if not self.id:
            self.slug = slugify(self.name)
        super(Supplier, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class PublishedReviewManager(models.Manager):
    use_for_related_fields = True

    def published(self, *args, **kwargs):
        return self.filter(status='published', *args, **kwargs)

class Review(TimeStampedModel):
    """ Model representing a Review """
    RATING_CHOICES = [(rating, rating) for rating in range(1, 6)]
    STATUS_CHOICES = [(state, state) for state in ('draft', 'published')]

    supplier = models.ForeignKey(Supplier)
    rating = models.PositiveIntegerField(choices=RATING_CHOICES)
    author = models.CharField(max_length=100)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='draft')
    content = models.TextField()

    objects = PublishedReviewManager()

    def __str__(self):
        return "{}: {}".format(self.supplier.name, self.created.strftime('%Y-%m-%d %X'))

energy/reviews/forms.py
from django.forms import ModelForm

from .models import Supplier, Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('author', 'rating', 'content')

energy/reviews/views.py
from django.views.generic import ListView, CreateView
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .models import Supplier, Review
from .forms import ReviewForm

class SupplierListView(ListView):
    model = Supplier

    def get_queryset(self):
        return Supplier.objects.order_by('name')


class SupplierReviewListView(ListView):
    model = Review

    def get_queryset(self):
        slug = self.kwargs.get('slug', None)
        return Review.objects.published().filter(supplier__slug=slug).order_by('-created')

    def get_context_data(self, **kwargs):
        context = super(SupplierReviewListView, self).get_context_data(**kwargs)
        context['supplier'] = get_object_or_404(Supplier, slug=self.kwargs.get('slug'))
        return context

def create_review(request, slug):
    supplier = get_object_or_404(Supplier, slug=slug)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            new_review = form.save(commit=False)
            new_review.supplier = supplier
            new_review.save()
            return HttpResponseRedirect(reverse('reviews:suppliers'))
    else:
        form = ReviewForm()
    return render(request, 'reviews/review_form.html', {'supplier': supplier, 'form': form})

energy/reviews/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
    <title>{% block title %}Supplier Reviews{% endblock %}</title>
</head>

<body>
    <div id="content">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

energy/reviews/templates/reviews/review_form.html
{% extends "base.html" %}

{% block title %}Review {{supplier.name}}{% endblock %}

{% block content %}
<h3>Review {{supplier.name}}</h3>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

energy/reviews/templates/reviews/review_list.html
{% extends "base.html" %}

{% block title %}{{ supplier.name }}{% endblock %}

{% block content %}
<h3>{{ supplier.name }}</h3>
<div class="container-fluid">
{% if object_list %}
    {% for review in object_list %}
    <div class="row">
        Author: {{ review.author }}<br />
        Rating: {{ review.rating }}<br />
        Content: {{ review.content }}<br />
        Submitted: {{ review.created|date:"SHORT_DATETIME_FORMAT" }}
        <p></p>
    </div>
    {% endfor %}
{% else %}
    <div class="row">
        <p>There are currently no reviews for this supplier</p>
    </div>
{% endif %}
    <p></p>
    <div class="row">
        <a href="{% url 'reviews:create_review' slug=supplier.slug %}">Write a review for {{ supplier.name }}</a>
    </div>
</div>
{% endblock %}

energy/reviews/templates/reviews/supplier_list.html
{% extends "base.html" %}

{% block title %}Suppliers{% endblock %}

{% block content %}
<h3>Suppliers</h3>
<div class="container-fluid">
    <div class="row">
    {% if object_list %}
        <p>View reviews for the following suppliers:</p>
        <ul>
            {% for supplier in object_list %}
            <li><a href="{% url 'reviews:supplier_reviews' supplier.slug %}">{{ supplier.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No suppliers are available</p>
    {% endif %}
    </div>
</div>
{% endblock %}